// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSI.Trivia.Shared.DbContexts;

#nullable disable

namespace SSI.Trivia.Shared.Migrations
{
    [DbContext(typeof(TriviaDbContext))]
    partial class TriviaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterMediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTieBreaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TieBreakerAnswerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadedAfterMediaBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAfterMediaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedMediaBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedMediaName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TieBreakerAnswerId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Answer", b =>
                {
                    b.HasOne("SSI.Trivia.Shared.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Question", b =>
                {
                    b.HasOne("SSI.Trivia.Shared.Models.Game", null)
                        .WithMany("Questions")
                        .HasForeignKey("GameId");

                    b.HasOne("SSI.Trivia.Shared.Models.Answer", "TieBreakerAnswer")
                        .WithMany()
                        .HasForeignKey("TieBreakerAnswerId");

                    b.Navigation("TieBreakerAnswer");
                });

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Game", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SSI.Trivia.Shared.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
